can:
  interface: "vcan0"
  daemon:
    ipc_socket_path: "/tmp/qhrr_can_server.sock"
    rx_timeout_s: 0.001
    tx_timeout_s: 0.001
    join_timeout_s: 1.0
    max_tx_queue_size: 4096
    send_block: false
    send_timeout_s: null
    connect_timeout_s: 5.0
