# config/app_config/config_paths.yaml
#
# Fixed project-wide config path registry.
# Other YAML files should not contain paths to sibling config files.

app:
  robot_controller: "config/app_config/robot_controller_config.yaml"
  subprocesses : "config/app_config/subprocesses.yaml

robot:
  can_device: "config/robot_config/can_device_config.yaml"
